---
title: "Text and Code"
format:
  closeread-html:
    cr-style:
      section-background-color: white
      narrative-background-color-sidebar: "#111111"
      narrative-text-color-sidebar: white
      narrative-font-family: 'Georgia, "Times New Roman", Times, serif'
      narrative-font-size: 1.25rem
      narrative-sidebar-width: minmax(400px, 1fr)
---

Certain types of text and code have similarities in how they're stored in a document: a *line* is well-defined in both and all of the formatting (including spaces and interesting punctuation) is meaningful. Because of this similarity, the two share the syntax that you'll use to work with them in Closeread.

\
\
\

## Working with Text

This is a poem. It's called "Bellringer", by Rita Dove.

| I was given a name, it came out of a book—
| I don’t know which. I’ve been told the Great Man
| could recite every title in order on its shelf.
| Well, I was born, and that’s a good thing,
| although I arrived on the day of his passing,
| 
| a day on which our country fell into mourning.
| This I heard over and over, from professors
| to farmers, even duel-scarred students;
| sometimes, in grand company, remarked upon
| in third person—a pretty way of saying
| 
| more than two men in a room means the third
| can be ignored, as I was when they spoke
| of my birth and Mr. Jefferson’s death
| in one breath, voices dusted with wonderment,
| faint sunlight quivering on a hidden breeze.

It starts with the narrator reflecting on their name and it's source - a book - as if it were predestined.

The author refers to their birth twice: one here...

... and again, further down.

The poem ends with lovely lyricism.


## Working with Code

This is an example of code that generates a scatterplot. It is written in `ggplot2`, a plotting library in the R language that implements the Grammar of Graphics of Leland Wilkinson. The core of the ggplot is the aesthetics mappings, which link columns of the `penguins` data frame to different visual aesthetics: location along the x-axis, location along the y-axis, color, and shape. The geometry, `geom_point`, describes the manner in which we will represent the observations on the plot. The final two layers polish the plot by modifying the axis labels and changing the theme of the plot frame to be in black and white.

```{r}
#| eval: false
library(ggplot2)
library(palmerpenguins)

ggplot(penguins, 
         aes(x = bill_length_mm, 
             y = bill_depth_mm,
             color = species,
             shape = species)) +
  geom_point() +
  labs(x = "Bill length (mm)", y = "Bill depth (mm)") +
  theme_bw()
```